version: '3'

services:
    mosquitto:
        image: eclipse-mosquitto:latest
        network_mode: 'host'
        user: 1000:1000
        volumes:
            - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
